Add awesome-lite-websites
jnv/lists pull request #198
Opened 2023-03-18 11:38 UTC by kelpwave

added awesome-lite-websites by mdibaiee :)

2023-03-19 21:16 UTC, jnv requested changes
Thank you for your contribution, Kelpwave! I'll be happy to merge your PR but I noticed there's an accidental change in entry for `graph-adversarial-learning-literature` on line 294; could you please revert that change? I'll then squash your commits.

2023-03-19 21:16 UTC, jnv commented on README.md
> +* [graph-adversarial-learning-literature](https://github.com/YingtongDou/graph-adversarial-learning-A list of lightweight versions of websites without all the bloatrature) – Adversarial learning pape
Look like this line was accidentally replaced. Could you please revert the change here?

2023-03-20 11:05 UTC, kelpwave commented
should be fixed now :)

2023-03-20 12:24 UTC, merged

2023-03-20 12:24 UTC, jnv commented
And merged. Thanks again!